### ISSUE TITLE
attempt to call field 'register_on_death' (a nil value)

### ISSUE THREAD

**Issue by Golutazem** [acmgit/distancer#3]
With Minetest and minetest_game 5.2.0, starting a world,
```
 ModError: Failed to load and run script from ~/.minetest/mods/distancer/init.lua:
~/.minetest/mods/distancer/init.lua:825: attempt to call field 'register_on_death' (a nil value)
stack traceback:
~/.minetest/mods/distancer/init.lua:825: in main chunk

```

**Comment by acmgit** [comment]
This is not a normal mod, this is a Client-Side-Mod and is independent from a game or server.
You have to move it into the directory clientmods. After them, you have to create a file with the name: mods.conf.
In this file you write the following line: load_mod_distancer = true and saves it.

Then enable client-side-mods in the settings of your minetest. When you then enter a new World or server and they don't locks client-side-mods (I have until now no server found, who locked a client-side-mod), you can use the distancer with the command .dis

You see, the regular chat-commands begins with a /<command>.
Chatcommands for a  Clientsidemod start usually with a .<command>

Greetings, Clyde.
